apiVersion: v1
kind: Service
metadata:
  name: phpbb-service
  namespace: 4kube
spec:
  type: NodePort
  selector:
    app: phpbb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
