apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpbb
  namespace: 4kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpbb
  template:
    metadata:
      labels:
        app: phpbb
    spec:
      containers:
        - name: phpbb
          image: bitnami/phpbb:latest
          env:
            - name: MARIADB_HOST
              value: "mysql"
            - name: PHPBB_DATABASE_NAME
              value: "mysql"
            - name: MARIADB_PORT
              value: "3306"
            - name: PHPBB_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: PHPBB_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
          ports:
            - containerPort: 80
          volumeMounts:
            - name: phpbb-persistent-storage
              mountPath: /bitnami/phpbb
      volumes:
        - name: phpbb-persistent-storage
          persistentVolumeClaim:
            claimName: phpbb-pv-claim
