# Service
apiVersion: v1
kind: Service
metadata:
  name: service-prestashop
  namespace: 4kube
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      nodePort: 30080
  selector:
    app: prestashop
